import {
  seedProducts,
  getTrendingProducts,
  getFeaturedProduct,
  getProductBySlug,
  getProductsByType,
  getProductsByPokemon,
  searchProducts,
  getProductsBySet,
  getProductsByCategory,
  getDeals,
  getGradedProducts,
  getSealedProducts,
  getVintageProducts,
  getAccessoryProducts,
  getProductsByRarity,
  getProductsByGrade,
  getRelatedProducts,
  getAllProducts,
  getFilteredProducts,
} from '@/seed/products';

export {
  seedProducts,
  getTrendingProducts,
  getFeaturedProduct,
  getProductBySlug,
  getProductsByType,
  getProductsByPokemon,
  searchProducts,
  getProductsBySet,
  getProductsByCategory,
  getDeals,
  getGradedProducts,
  getSealedProducts,
  getVintageProducts,
  getAccessoryProducts,
  getProductsByRarity,
  getProductsByGrade,
  getRelatedProducts,
  getAllProducts,
  getFilteredProducts,
};