// Products data access - uses Prisma (Neon DB)
export {
  getAllProducts,
  getProductById,
  getProductBySlug,
  createProduct,
  updateProduct,
  deleteProduct,
  getProductsByType,
  getProductsByPokemon,
  getProductsBySet,
  getProductsByCategory,
  getTrendingProducts,
  getFeaturedProduct,
  getDeals,
  getGradedProducts,
  getSealedProducts,
  getVintageProducts,
  getAccessoryProducts,
  getRelatedProducts,
  searchProducts,
  getProductStats,
} from '@/lib/admin/db';
