import { Product } from '@/types';

export const pokeCollectProducts: Product[] = [
  {
    id: 'pc-001',
    name: 'Pokemon - Circular Diorama Collection 2 - Sparkling Moment - Blind Box',
    slug: 'pokemon-circular-diorama-collection-2-sparkling-moment',
    description: 'Circular Diorama Collection 2 featuring Sparkling Moment Pokemon figurines. Each blind box contains one random figurine from the collection.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 15,
    images: [
      'https://poke-collect.com/cdn/shop/files/CDrement.png?v=1783617888&width=300',
      'https://poke-collect.com/cdn/shop/files/CDmim.png?v=1783617888&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-002',
    name: 'Pokemon - Decorative Frame 2 - Beyond the Boundaries - Blind Box',
    slug: 'pokemon-decorative-frame-2-beyond-the-boundaries',
    description: 'Decorative Frame 2 featuring Beyond the Boundaries Pokemon figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 21,
    images: [
      'https://poke-collect.com/cdn/shop/files/decoframe.png?v=1783620914&width=300',
      'https://poke-collect.com/cdn/shop/files/decoframelux.png?v=1783620914&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-003',
    name: 'Pokemon - Diamond Dust Blind Box',
    slug: 'pokemon-diamond-dust-blind-box',
    description: 'Diamond Dust collection featuring sparkling Pokemon figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 20,
    images: [
      'https://poke-collect.com/cdn/shop/files/DD.png?v=1772558573&width=300',
      'https://poke-collect.com/cdn/shop/files/DDGla.png?v=1772558579&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-004',
    name: 'Pokemon - Pocket Bonsai 3 Blind Box',
    slug: 'pokemon-pocket-bonsai-3-blind-box',
    description: 'Pocket Bonsai 3 collection featuring miniature Pokemon bonsai figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 0,
    images: [
      'https://poke-collect.com/cdn/shop/files/bonsai3.png?v=1772558602&width=300',
      'https://poke-collect.com/cdn/shop/files/artblind.jpg?v=1772558603&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-005',
    name: 'Pokemon - DesQ Battle On Desk - Blind Box',
    slug: 'pokemon-desq-battle-on-desk-blind-box',
    description: 'DesQ Battle On Desk collection featuring battle scene Pokemon figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 14.95,
    currency: 'USD',
    stock: 18,
    images: [
      'https://poke-collect.com/cdn/shop/files/batle_desk.png?v=1746295177&width=300',
      'https://poke-collect.com/cdn/shop/files/1250874623.jpg?v=1746295177&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-006',
    name: 'Pokemon Gemstone Collection - Shining Miracle Of Mystery Blind Box',
    slug: 'pokemon-gemstone-collection-shining-miracle-of-mystery-blind-box',
    description: 'Gemstone Collection featuring Shining Miracle of Mystery Pokemon figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 3,
    images: [
      'https://poke-collect.com/cdn/shop/files/gem.png?v=1746295248&width=300',
      'https://poke-collect.com/cdn/shop/files/554648548.jpg?v=1746295248&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-007',
    name: 'Pokemon - Neon Party Blind Box',
    slug: 'pokemon-neon-party-blind-box',
    description: 'Neon Party collection featuring vibrant neon-styled Pokemon figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 0,
    images: [
      'https://poke-collect.com/cdn/shop/files/NP_f2e19006-0aad-4181-bccb-3445f38a23ab.png?v=1772558613&width=300',
      'https://poke-collect.com/cdn/shop/files/NPTox_4927f890-a52e-488d-8545-afadb4ac573a.png?v=1772558620&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-008',
    name: 'Pokemon - Soft and Swaying Decoration - Blind Box',
    slug: 'pokemon-soft-and-swaying-decoration-blind-box',
    description: 'Soft and Swaying Decoration collection featuring gentle-moving Pokemon figurines. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 7,
    images: [
      'https://poke-collect.com/cdn/shop/files/SS_ed3fc07d-4019-46d0-9711-f279d341b8f5.png?v=1772558568&width=300',
      'https://poke-collect.com/cdn/shop/files/ssmew.png?v=1772558575&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-009',
    name: 'Pokemon - Little Night 2 - A Little Mischief in the Dark - Blind Box',
    slug: 'pokemon-little-night-2-a-little-mischief-in-the-dark-blind-box',
    description: 'Little Night 2 collection featuring adorable Pokemon figurines in dark-themed settings. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 1,
    images: [
      'https://poke-collect.com/cdn/shop/files/LN.png?v=1772558582&width=300',
      'https://poke-collect.com/cdn/shop/files/LNGeng.png?v=1772558589&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-010',
    name: 'Pokemon - Lantern Diorama Blind Box',
    slug: 'pokemon-lantern-diorama-blind-box',
    description: 'Lantern Diorama collection featuring Pokemon figurines with lantern-themed dioramas. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 0,
    images: [
      'https://poke-collect.com/cdn/shop/files/LD.png?v=1772558647&width=300',
      'https://poke-collect.com/cdn/shop/files/LDPika.png?v=1772558652&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-011',
    name: 'Pokemon - Swing Vignette - A Moment of Flickering Pokemon - Blind Box',
    slug: 'pokemon-swing-vignette-a-moment-of-flickering-pokemon-blind-box',
    description: 'Swing Vignette collection featuring Pokemon figurines in swinging vignette displays. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 16.95,
    currency: 'USD',
    stock: 0,
    images: [
      'https://poke-collect.com/cdn/shop/files/SV4.png?v=1772558569&width=300',
      'https://poke-collect.com/cdn/shop/files/SVChar.png?v=1772558578&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pc-012',
    name: 'Pokemon - Terrarium 15 Blind Box',
    slug: 'pokemon-terrarium-15-blind-box',
    description: 'Terrarium 15 collection featuring Pokemon figurines in terrarium-style displays. Each blind box contains one random figurine.',
    productType: 'accessory',
    category: 'accessories',
    price: 17.95,
    currency: 'USD',
    stock: 0,
    images: [
      'https://poke-collect.com/cdn/shop/files/Untitled_deac68df-dba9-4a71-8781-d170a8bf5e29.png?v=1769804869&width=300',
      'https://poke-collect.com/cdn/shop/files/zardy.png?v=1769804869&width=300',
    ],
    condition: 'Factory Sealed',
    language: 'Japanese',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
