import { Product } from '@/types';

export const pokeCollectSealedProducts: Product[] = [
  // === MEGA EVOLUTION: DELTA REIGN ===
  {
    id: 'pcs-001',
    name: 'Mega Evolution: Delta Reign Booster Box',
    slug: 'mega-evolution-delta-reign-booster-box',
    description: 'Factory sealed Mega Evolution: Delta Reign Booster Box. 36 packs per box.',
    productType: 'sealed',
    category: 'sealed',
    price: 249.95,
    currency: 'USD',
    stock: 10,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/DRNBB_360x504.png?v=1787606560'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Delta Reign',
    setSlug: 'mega-evolution-delta-reign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-002',
    name: 'Mega Evolution: Delta Reign Elite Trainer Box',
    slug: 'mega-evolution-delta-reign-elite-trainer-box',
    description: 'Factory sealed Mega Evolution: Delta Reign Elite Trainer Box. Includes 9 booster packs, sleeves, and more.',
    productType: 'sealed',
    category: 'sealed',
    price: 119.95,
    currency: 'USD',
    stock: 15,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/DRNETB_360x504.png?v=1787606600'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Delta Reign',
    setSlug: 'mega-evolution-delta-reign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-003',
    name: 'Mega Evolution: Delta Reign Booster Bundle',
    slug: 'mega-evolution-delta-reign-booster-bundle',
    description: 'Factory sealed Mega Evolution: Delta Reign Booster Bundle. 6 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 49.95,
    currency: 'USD',
    stock: 20,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/DRNBUN_360x504.png?v=1787606646'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Delta Reign',
    setSlug: 'mega-evolution-delta-reign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-004',
    name: 'Mega Evolution: Delta Reign 3-Pack Blister',
    slug: 'mega-evolution-delta-reign-3-pack-blister',
    description: 'Factory sealed Mega Evolution: Delta Reign 3-Pack Blister. 3 booster packs with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 24.95,
    currency: 'USD',
    stock: 25,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/DRN3PK_360x504.png?v=1787606690'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Delta Reign',
    setSlug: 'mega-evolution-delta-reign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-005',
    name: 'Mega Evolution: Delta Reign Single Pack Blister',
    slug: 'mega-evolution-delta-reign-single-pack-blister',
    description: 'Factory sealed Mega Evolution: Delta Reign Single Pack Blister. 1 booster pack with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 8.49,
    currency: 'USD',
    stock: 30,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/DRN1PK_360x504.png?v=1787606736'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Delta Reign',
    setSlug: 'mega-evolution-delta-reign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-006',
    name: 'Mega Evolution: Delta Reign Booster Pack',
    slug: 'mega-evolution-delta-reign-booster-pack',
    description: 'Single Mega Evolution: Delta Reign Booster Pack. 10 cards per pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 7.95,
    currency: 'USD',
    stock: 50,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/DRNBP_360x504.png?v=1787606781'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Delta Reign',
    setSlug: 'mega-evolution-delta-reign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // === MEGA EVOLUTION: PITCH BLACK ===
  {
    id: 'pcs-007',
    name: 'Mega Evolution: Pitch Black Booster Box',
    slug: 'mega-evolution-pitch-black-booster-box',
    description: 'Factory sealed Mega Evolution: Pitch Black Booster Box. 36 packs per box.',
    productType: 'sealed',
    category: 'sealed',
    price: 187.95,
    compareAtPrice: 199.95,
    currency: 'USD',
    stock: 12,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_bb_ad_360x504.png?v=1783632716'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-008',
    name: 'Mega Evolution: Pitch Black Elite Trainer Box',
    slug: 'mega-evolution-pitch-black-elite-trainer-box',
    description: 'Factory sealed Mega Evolution: Pitch Black Elite Trainer Box. Includes 9 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 69.95,
    compareAtPrice: 84.95,
    currency: 'USD',
    stock: 18,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_etb_ad_360x504.png?v=1783633046'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-009',
    name: 'Mega Evolution: Pitch Black Booster Bundle',
    slug: 'mega-evolution-pitch-black-booster-bundle',
    description: 'Factory sealed Mega Evolution: Pitch Black Booster Bundle. 6 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 39.95,
    compareAtPrice: 44.95,
    currency: 'USD',
    stock: 22,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_bun_ad_360x504.png?v=1783632793'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-010',
    name: 'Mega Evolution: Pitch Black 3-Pack Blister',
    slug: 'mega-evolution-pitch-black-3-pack-blister',
    description: 'Factory sealed Mega Evolution: Pitch Black 3-Pack Blister. 3 booster packs with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 21.95,
    currency: 'USD',
    stock: 28,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_3_ad_360x504.png?v=1783632642'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-011',
    name: 'Mega Evolution: Pitch Black Single Pack Blister',
    slug: 'mega-evolution-pitch-black-single-pack-blister',
    description: 'Factory sealed Mega Evolution: Pitch Black Single Pack Blister. 1 booster pack with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 6.95,
    compareAtPrice: 8.95,
    currency: 'USD',
    stock: 35,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_single_ad_360x504.png?v=1783633129'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-012',
    name: 'Mega Evolution: Pitch Black Sleeved Booster Pack',
    slug: 'mega-evolution-pitch-black-sleeved-booster-pack',
    description: 'Single Mega Evolution: Pitch Black Sleeved Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 5.95,
    currency: 'USD',
    stock: 40,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_sleeve_ad_360x504.png?v=1783633213'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-013',
    name: 'Mega Evolution: Pitch Black Booster Pack',
    slug: 'mega-evolution-pitch-black-booster-pack',
    description: 'Single Mega Evolution: Pitch Black Booster Pack. 10 cards per pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 5.95,
    currency: 'USD',
    stock: 45,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pb_bp_ad_360x504.png?v=1783632933'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Pitch Black',
    setSlug: 'mega-evolution-pitch-black',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // === MEGA EVOLUTION: CHAOS RISING ===
  {
    id: 'pcs-014',
    name: 'Mega Evolution: Chaos Rising Booster Box',
    slug: 'mega-evolution-chaos-rising-booster-box',
    description: 'Factory sealed Mega Evolution: Chaos Rising Booster Box. 36 packs per box.',
    productType: 'sealed',
    category: 'sealed',
    price: 186.95,
    compareAtPrice: 214.95,
    currency: 'USD',
    stock: 10,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/crb_bb_2_360x504.png?v=1778856730'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Chaos Rising',
    setSlug: 'mega-evolution-chaos-rising',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-015',
    name: 'Mega Evolution: Chaos Rising Booster Bundle',
    slug: 'mega-evolution-chaos-rising-booster-bundle',
    description: 'Factory sealed Mega Evolution: Chaos Rising Booster Bundle. 6 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 37.95,
    compareAtPrice: 42.95,
    currency: 'USD',
    stock: 18,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/cr_bun_360x504.png?v=1778856731'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Chaos Rising',
    setSlug: 'mega-evolution-chaos-rising',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-016',
    name: 'Mega Evolution: Chaos Rising 3-Pack Blister',
    slug: 'mega-evolution-chaos-rising-3-pack-blister',
    description: 'Factory sealed Mega Evolution: Chaos Rising 3-Pack Blister. 3 booster packs with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 19.95,
    currency: 'USD',
    stock: 25,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/cr_3p_360x504.png?v=1778856731'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Chaos Rising',
    setSlug: 'mega-evolution-chaos-rising',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-017',
    name: 'Mega Evolution: Chaos Rising Single Pack Blister',
    slug: 'mega-evolution-chaos-rising-single-pack-blister',
    description: 'Factory sealed Mega Evolution: Chaos Rising Single Pack Blister. 1 booster pack with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 7.49,
    currency: 'USD',
    stock: 30,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/cr_spb_360x504.png?v=1778856730'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Chaos Rising',
    setSlug: 'mega-evolution-chaos-rising',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-018',
    name: 'Mega Evolution: Chaos Rising Sleeved Booster Pack',
    slug: 'mega-evolution-chaos-rising-sleeved-booster-pack',
    description: 'Single Mega Evolution: Chaos Rising Sleeved Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 6.95,
    currency: 'USD',
    stock: 40,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/cr_sbp_2_360x504.png?v=1778857408'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Chaos Rising',
    setSlug: 'mega-evolution-chaos-rising',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // === MEGA EVOLUTION: PERFECT ORDER ===
  {
    id: 'pcs-019',
    name: 'Mega Evolution: Perfect Order Booster Box',
    slug: 'mega-evolution-perfect-order-booster-box',
    description: 'Factory sealed Mega Evolution: Perfect Order Booster Box. 36 packs per box.',
    productType: 'sealed',
    category: 'sealed',
    price: 171.95,
    compareAtPrice: 179.95,
    currency: 'USD',
    stock: 12,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pobb_360x504.png?v=1767887844'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Perfect Order',
    setSlug: 'mega-evolution-perfect-order',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-020',
    name: 'Mega Evolution: Perfect Order Booster Bundle',
    slug: 'mega-evolution-perfect-order-booster-bundle',
    description: 'Factory sealed Mega Evolution: Perfect Order Booster Bundle. 6 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 39.95,
    currency: 'USD',
    stock: 20,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pobun_360x504.png?v=1767888020'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Perfect Order',
    setSlug: 'mega-evolution-perfect-order',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-021',
    name: 'Mega Evolution: Perfect Order 3-Pack Blister',
    slug: 'mega-evolution-perfect-order-3-pack-blister',
    description: 'Factory sealed Mega Evolution: Perfect Order 3-Pack Blister. 3 booster packs with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 19.95,
    currency: 'USD',
    stock: 25,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/po3_742178e9-d147-4fc5-9139-afb4a7860a15_360x504.png?v=1770148214'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Perfect Order',
    setSlug: 'mega-evolution-perfect-order',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-022',
    name: 'Mega Evolution: Perfect Order Single Pack Blister',
    slug: 'mega-evolution-perfect-order-single-pack-blister',
    description: 'Factory sealed Mega Evolution: Perfect Order Single Pack Blister. 1 booster pack with promo card.',
    productType: 'sealed',
    category: 'sealed',
    price: 7.95,
    currency: 'USD',
    stock: 30,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/posingle_304e0ba4-7467-4274-b72f-e1c143512103_360x504.png?v=1770148111'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Perfect Order',
    setSlug: 'mega-evolution-perfect-order',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-023',
    name: 'Mega Evolution: Perfect Order Sleeved Booster Pack',
    slug: 'mega-evolution-perfect-order-sleeved-booster-pack',
    description: 'Single Mega Evolution: Perfect Order Sleeved Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 6.95,
    currency: 'USD',
    stock: 40,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/posleeeve_796a30e1-b82e-414f-a9a3-241d0c684d91_360x504.png?v=1770148054'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Perfect Order',
    setSlug: 'mega-evolution-perfect-order',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-024',
    name: 'Mega Evolution: Perfect Order Booster Pack',
    slug: 'mega-evolution-perfect-order-booster-pack',
    description: 'Single Mega Evolution: Perfect Order Booster Pack. 10 cards per pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 4.95,
    currency: 'USD',
    stock: 50,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/pobp_360x504.png?v=1767887970'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Perfect Order',
    setSlug: 'mega-evolution-perfect-order',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // === JAPANESE PRODUCTS ===
  {
    id: 'pcs-025',
    name: 'Japanese Storm Emeralda Booster Box',
    slug: 'japanese-storm-emeralda-booster-box',
    description: 'Factory sealed Japanese Storm Emeralda Booster Box. Japanese text.',
    productType: 'sealed',
    category: 'sealed',
    price: 149.95,
    compareAtPrice: 184.95,
    currency: 'USD',
    stock: 8,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/sebb_360x504.png?v=1785966257'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Storm Emeralda',
    setSlug: 'storm-emeralda',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-026',
    name: 'Japanese Pokemon Center - Special Box Collection - Fukuoka',
    slug: 'japanese-pokemon-center-special-box-collection-fukuoka',
    description: 'Japanese Pokemon Center Special Box Collection exclusive to Fukuoka.',
    productType: 'sealed',
    category: 'sealed',
    price: 169.95,
    compareAtPrice: 219.95,
    currency: 'USD',
    stock: 5,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/scbFukuoka_360x504.png?v=1785256692'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Pokemon Center Special Box',
    setSlug: 'pokemon-center-special-box',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-027',
    name: 'Japanese Pokemon Center - Special Box Collection - Hiroshima',
    slug: 'japanese-pokemon-center-special-box-collection-hiroshima',
    description: 'Japanese Pokemon Center Special Box Collection exclusive to Hiroshima.',
    productType: 'sealed',
    category: 'sealed',
    price: 184.95,
    compareAtPrice: 229.95,
    currency: 'USD',
    stock: 5,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/sbchiroshima_360x504.png?v=1785256724'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Pokemon Center Special Box',
    setSlug: 'pokemon-center-special-box',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-028',
    name: 'Japanese Pokemon Center - Special Box Collection - Tohoku',
    slug: 'japanese-pokemon-center-special-box-collection-tohoku',
    description: 'Japanese Pokemon Center Special Box Collection exclusive to Tohoku.',
    productType: 'sealed',
    category: 'sealed',
    price: 149.95,
    compareAtPrice: 189.95,
    currency: 'USD',
    stock: 5,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/scbtohoku_360x504.png?v=1785256659'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Pokemon Center Special Box',
    setSlug: 'pokemon-center-special-box',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-029',
    name: 'Japanese Abyss Eye Booster Box',
    slug: 'japanese-abyss-eye-booster-box',
    description: 'Factory sealed Japanese Abyss Eye Booster Box.',
    productType: 'sealed',
    category: 'sealed',
    price: 87.95,
    compareAtPrice: 124.95,
    currency: 'USD',
    stock: 10,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/aae_bb_360x504.png?v=1779977164'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Abyss Eye',
    setSlug: 'abyss-eye',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-030',
    name: 'Japanese Abyss Eye Booster Pack',
    slug: 'japanese-abyss-eye-booster-pack',
    description: 'Single Japanese Abyss Eye Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 3.49,
    currency: 'USD',
    stock: 50,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/aeboosterpack_360x504.png?v=1783544157'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Abyss Eye',
    setSlug: 'abyss-eye',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-031',
    name: 'Japanese Ninja Spinner Booster Box',
    slug: 'japanese-ninja-spinner-booster-box',
    description: 'Factory sealed Japanese Ninja Spinner Booster Box.',
    productType: 'sealed',
    category: 'sealed',
    price: 99.95,
    compareAtPrice: 119.95,
    currency: 'USD',
    stock: 8,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/ns_bb_360x504.png?v=1773925407'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Ninja Spinner',
    setSlug: 'ninja-spinner',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-032',
    name: 'Japanese Ninja Spinner Booster Pack',
    slug: 'japanese-ninja-spinner-booster-pack',
    description: 'Single Japanese Ninja Spinner Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 3.95,
    currency: 'USD',
    stock: 45,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/Untitled_6be2158c-0c97-48a9-b5fe-a296929b4d3a_360x504.png?v=1773688019'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Ninja Spinner',
    setSlug: 'ninja-spinner',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-033',
    name: 'Japanese Munikis Zero Booster Box',
    slug: 'japanese-munikis-zero-booster-box',
    description: 'Factory sealed Japanese Munikis Zero Booster Box.',
    productType: 'sealed',
    category: 'sealed',
    price: 87.95,
    compareAtPrice: 99.95,
    currency: 'USD',
    stock: 8,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/mzbb_7b9f530d-dc02-48ab-8430-bb467621c830_360x504.png?v=1770317932'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Munikis Zero',
    setSlug: 'munikis-zero',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-034',
    name: 'Japanese Munikis Zero Booster Pack',
    slug: 'japanese-munikis-zero-booster-pack',
    description: 'Single Japanese Munikis Zero Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 2.95,
    currency: 'USD',
    stock: 50,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/mzbp_d9b68391-b79a-469b-8038-9bf5cb4a6674_360x504.png?v=1770318476'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Munikis Zero',
    setSlug: 'munikis-zero',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-035',
    name: 'Japanese Mega Dream ex Booster Box',
    slug: 'japanese-mega-dream-ex-booster-box',
    description: 'Factory sealed Japanese Mega Dream ex Booster Box.',
    productType: 'sealed',
    category: 'sealed',
    price: 123.95,
    compareAtPrice: 149.95,
    currency: 'USD',
    stock: 6,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/megadreambb_87b31ef2-639a-4044-8a3c-eaf538053bc8_360x504.png?v=1764787791'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Mega Dream ex',
    setSlug: 'mega-dream-ex',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-036',
    name: 'Japanese Mega Dream ex Booster Pack',
    slug: 'japanese-mega-dream-ex-booster-pack',
    description: 'Single Japanese Mega Dream ex Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 13.49,
    currency: 'USD',
    stock: 25,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/megabp_5093a790-4ee8-432c-bd50-e9bff9986d8a_360x504.png?v=1764883048'],
    condition: 'Factory Sealed',
    language: 'Japanese',
    set: 'Mega Dream ex',
    setSlug: 'mega-dream-ex',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // === SPECIAL COLLECTIONS & TINS ===
  {
    id: 'pcs-037',
    name: 'Pokémon 30th Celebration Tech Sticker Collection (Alolan Exeggutor)',
    slug: 'pokemon-30th-celebration-tech-sticker-collection-alolan-exeggutor',
    description: 'Pokemon 30th Anniversary Tech Sticker Collection featuring Alolan Exeggutor.',
    productType: 'sealed',
    category: 'sealed',
    price: 48.95,
    currency: 'USD',
    stock: 12,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/30thteche_360x504.png?v=1782919371'],
    condition: 'Factory Sealed',
    language: 'English',
    set: '30th Anniversary',
    setSlug: '30th-anniversary',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-038',
    name: 'Pokémon 30th Celebration Poster Collection',
    slug: 'pokemon-30th-celebration-poster-collection',
    description: 'Pokemon 30th Anniversary Poster Collection with booster packs and posters.',
    productType: 'sealed',
    category: 'sealed',
    price: 54.95,
    currency: 'USD',
    stock: 10,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/Pokemon_TCG_30th_Celebration_Poster_Collection_EN-copy-scaled-removebg_360x504.png?v=1782919145'],
    condition: 'Factory Sealed',
    language: 'English',
    set: '30th Anniversary',
    setSlug: '30th-anniversary',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-039',
    name: 'First Partner Illustration Collection - Series 3',
    slug: 'first-partner-illustration-collection-series-3',
    description: 'First Partner Illustration Collection Series 3 featuring starter Pokemon.',
    productType: 'sealed',
    category: 'sealed',
    price: 31.95,
    currency: 'USD',
    stock: 15,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/fps3_360x504.png?v=1786570126'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'First Partner',
    setSlug: 'first-partner',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-040',
    name: 'First Partner Illustration Collection - Series 2',
    slug: 'first-partner-illustration-collection-series-2',
    description: 'First Partner Illustration Collection Series 2 featuring starter Pokemon.',
    productType: 'sealed',
    category: 'sealed',
    price: 28.95,
    compareAtPrice: 29.95,
    currency: 'USD',
    stock: 12,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/fpo2_360x504.png?v=1781883999'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'First Partner',
    setSlug: 'first-partner',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-041',
    name: 'Pokemon: 2026 Q1 Mini Portfolio (Phantasmal Flames Booster Pack Included)',
    slug: 'pokemon-2026-q1-mini-portfolio-phantasmal-flames',
    description: 'Pokemon 2026 Q1 Mini Portfolio with included Phantasmal Flames Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 11.95,
    currency: 'USD',
    stock: 20,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/673294_in_1000x1000_31cd599e-d62a-4435-8a99-076cf7853566_360x504.jpg?v=1778870981'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Phantasmal Flames',
    setSlug: 'phantasmal-flames',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-042',
    name: 'Lumiose City Mini Tins (Set of 5)',
    slug: 'lumiose-city-mini-tins-set-of-5',
    description: 'Lumiose City Mini Tins Set of 5. Each tin contains 2 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 64.95,
    currency: 'USD',
    stock: 10,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/Untitled_1_d668c713-55f1-4af1-bbc3-ae22d14224ff_360x504.png?v=1781737491'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Lumiose City',
    setSlug: 'lumiose-city',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-043',
    name: 'Mega Moonlit Tin - Mega Gengar ex',
    slug: 'mega-moonlit-tin-mega-gengar-ex',
    description: 'Mega Moonlit Tin featuring Mega Gengar ex with booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 32.95,
    currency: 'USD',
    stock: 12,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/mega_gen_360x504.png?v=1780947601'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Moonlit',
    setSlug: 'mega-moonlit',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-044',
    name: 'Mega Lucario ex League Battle Deck',
    slug: 'mega-lucario-ex-league-battle-deck',
    description: 'Mega Lucario ex League Battle Deck ready-to-play with 60 cards.',
    productType: 'sealed',
    category: 'sealed',
    price: 14.49,
    compareAtPrice: 29.95,
    currency: 'USD',
    stock: 18,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/lucario_league_2_360x504.png?v=1778863852'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'League Battle Deck',
    setSlug: 'league-battle-deck',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-045',
    name: 'Mega Zygarde ex Premium Collection',
    slug: 'mega-zygarde-ex-premium-collection',
    description: 'Mega Zygarde ex Premium Collection with booster packs and premium card.',
    productType: 'sealed',
    category: 'sealed',
    price: 50.95,
    currency: 'USD',
    stock: 10,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/mega_zyg_360x504.png?v=1779737106'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Premium Collection',
    setSlug: 'premium-collection',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-046',
    name: 'Pokémon Day 2026 Collection',
    slug: 'pokemon-day-2026-collection',
    description: 'Pokemon Day 2026 special collection with exclusive items.',
    productType: 'sealed',
    category: 'sealed',
    price: 37.95,
    currency: 'USD',
    stock: 15,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/2026pcday_360x504.png?v=1769722020'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Pokemon Day 2026',
    setSlug: 'pokemon-day-2026',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-047',
    name: 'Mega Evolution: Ascended Heroes Booster Pack',
    slug: 'mega-evolution-ascended-heroes-booster-pack',
    description: 'Single Mega Evolution: Ascended Heroes Booster Pack.',
    productType: 'sealed',
    category: 'sealed',
    price: 14.95,
    currency: 'USD',
    stock: 30,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/asche_a2b271e1-25cf-4404-9ca2-796289e4e2c4_360x504.png?v=1775846624'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Mega Evolution: Ascended Heroes',
    setSlug: 'mega-evolution-ascended-heroes',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pcs-048',
    name: 'Scarlet & Violet: Destined Rivals Booster Bundle',
    slug: 'scarlet-violet-destined-rivals-booster-bundle',
    description: 'Factory sealed Scarlet & Violet: Destined Rivals Booster Bundle. 6 booster packs.',
    productType: 'sealed',
    category: 'sealed',
    price: 68.95,
    currency: 'USD',
    stock: 15,
    images: ['https://cdn.shopify.com/s/files/1/0468/5299/7280/files/drbun_741f076f-2761-4991-be8b-d62fdd53a047_360x504.png?v=1743101253'],
    condition: 'Factory Sealed',
    language: 'English',
    set: 'Scarlet & Violet: Destined Rivals',
    setSlug: 'scarlet-violet-destined-rivals',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
