import { PokemonSet } from '@/types';

export const seedSets: PokemonSet[] = [
  {
    id: 'set-001',
    name: 'Evolving Skies',
    slug: 'evolving-skies',
    logo: '/sets/evolving-skies-logo.png',
    image: '/sets/evolving-skies.jpg',
    releaseDate: '2021-08-27',
    totalCards: 237,
    series: 'Sword & Shield',
  },
  {
    id: 'set-002',
    name: 'Scarlet & Violet',
    slug: 'scarlet-violet',
    logo: '/sets/scarlet-violet-logo.png',
    image: '/sets/scarlet-violet.jpg',
    releaseDate: '2023-03-31',
    totalCards: 198,
    series: 'Scarlet & Violet',
  },
  {
    id: 'set-003',
    name: 'Pokémon 151',
    slug: 'pokemon-151',
    logo: '/sets/pokemon-151-logo.png',
    image: '/sets/pokemon-151.jpg',
    releaseDate: '2023-09-22',
    totalCards: 165,
    series: 'Scarlet & Violet',
  },
  {
    id: 'set-004',
    name: 'Lost Origin',
    slug: 'lost-origin',
    logo: '/sets/lost-origin-logo.png',
    image: '/sets/lost-origin.jpg',
    releaseDate: '2022-09-09',
    totalCards: 217,
    series: 'Sword & Shield',
  },
  {
    id: 'set-005',
    name: 'Silver Tempest',
    slug: 'silver-tempest',
    logo: '/sets/silver-tempest-logo.png',
    image: '/sets/silver-tempest.jpg',
    releaseDate: '2022-11-11',
    totalCards: 195,
    series: 'Sword & Shield',
  },
  {
    id: 'set-006',
    name: 'Crown Zenith',
    slug: 'crown-zenith',
    logo: '/sets/crown-zenith-logo.png',
    image: '/sets/crown-zenith.jpg',
    releaseDate: '2023-01-20',
    totalCards: 159,
    series: 'Sword & Shield',
  },
  {
    id: 'set-007',
    name: 'Paldea Evolved',
    slug: 'paldea-evolved',
    logo: '/sets/paldea-evolved-logo.png',
    image: '/sets/paldea-evolved.jpg',
    releaseDate: '2023-06-09',
    totalCards: 193,
    series: 'Scarlet & Violet',
  },
  {
    id: 'set-008',
    name: 'Obsidian Flames',
    slug: 'obsidian-flames',
    logo: '/sets/obsidian-flames-logo.png',
    image: '/sets/obsidian-flames.jpg',
    releaseDate: '2023-08-11',
    totalCards: 190,
    series: 'Scarlet & Violet',
  },
  {
    id: 'set-009',
    name: '151 Japanese',
    slug: '151-japanese',
    logo: '/sets/151-japanese-logo.png',
    image: '/sets/151-japanese.jpg',
    releaseDate: '2023-06-16',
    totalCards: 165,
    series: 'Scarlet & Violet',
  },
  {
    id: 'set-010',
    name: 'Celebrations',
    slug: 'celebrations',
    logo: '/sets/celebrations-logo.png',
    image: '/sets/celebrations.jpg',
    releaseDate: '2021-10-08',
    totalCards: 25,
    series: 'Sword & Shield',
  },
  {
    id: 'set-011',
    name: 'Shining Fates',
    slug: 'shining-fates',
    logo: '/sets/shining-fates-logo.png',
    image: '/sets/shining-fates.jpg',
    releaseDate: '2021-02-19',
    totalCards: 122,
    series: 'Sword & Shield',
  },
  {
    id: 'set-012',
    name: 'Vivid Voltage',
    slug: 'vivid-voltage',
    logo: '/sets/vivid-voltage-logo.png',
    image: '/sets/vivid-voltage.jpg',
    releaseDate: '2020-11-13',
    totalCards: 185,
    series: 'Sword & Shield',
  },
];

export function getSets(): PokemonSet[] {
  return seedSets;
}

export function getSetBySlug(slug: string): PokemonSet | undefined {
  return seedSets.find(set => set.slug === slug);
}
