// Admin store - uses Prisma for database operations
// Re-exports Prisma-based functions for backward compatibility

export {
  getAllProducts,
  getProductById,
  getProductBySlug,
  createProduct,
  updateProduct,
  deleteProduct,
  getProductStats,
  getAllPokemon,
  getPokemonById,
  getPokemonBySlug,
  getPopularPokemon,
  createPokemon,
  updatePokemon,
  deletePokemon,
  getAllSets,
  getSetById,
  getSetBySlug,
  createSet,
  updateSet,
  deleteSet,
  getAllCategories,
  getCategoryById,
  getCategoryBySlug,
  createCategory,
  updateCategory,
  deleteCategory,
  getAllSellers,
  getSellerById,
  searchProducts,
  getProductsByType,
  getProductsByPokemon,
  getProductsBySet,
  getProductsByCategory,
  getTrendingProducts,
  getFeaturedProduct,
  getDeals,
  getGradedProducts,
  getSealedProducts,
  getVintageProducts,
  getAccessoryProducts,
  getRelatedProducts,
  getAllProductsRaw,
} from '@/lib/admin/db';
